### PR TITLE
Add alibaba ci

### PR DESCRIPTION
**Pull request by amitsagtani97**
### Description
Integrate Alibaba cloud for the Public cloud CI

Depends on - https://github.com/cloud-bulldozer/scale-ci-deploy/pull/185
Live playground - http://amitsagtani97-add-alibaba-ci-airflow.apps.sailplane.perf.lab.eng.rdu2.redhat.com/home

### CODE REVIEW

**Comment by rsevilla87** [comment]
@amitsagtani97, needs rebase

**Comment by rsevilla87** [comment]
@mohit-sheth @Harshith-umesh, can you take a look?

**Review by mohit-sheth — APPROVED** [review]
lgtm

**Review by Harshith-umesh — APPROVED** [review]
LGTM!

**Pull request merged**
