### PR TITLE
Update Managed Services Runs to not to be concurrents

### PR DESCRIPTION
**Pull request by morenod**

### CODE REVIEW

**Review by smalleni — COMMENTED** [review]
@morenod Is there some "airflow thingy" that prevents concurrent runs of a dag as well. Since users could manually trigger the same dag concurrently.

**Comment by morenod** [comment]
> @morenod Is there some "airflow thingy" that prevents concurrent runs of a dag as well. Since users could manually trigger the same dag concurrently.

Concurrent builds of the same DAG are disabled by default on airflow. if somebody trigger a DAG when there is another one running, it will be waiting until the running one ends

**Comment by smalleni** [comment]
> > @morenod Is there some "airflow thingy" that prevents concurrent runs of a dag as well. Since users could manually trigger the same dag concurrently.
> 
> Concurrent builds of the same DAG are disabled by default on airflow. if somebody trigger a DAG when there is another one running, it will be waiting until the running one ends

Gotcha, but what is someone triggers rosa ovn and rosa sdn at the same time. We would still run into the `osdCcsAdmin` credentials issue right?

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@smalleni Mind giving this a quick review/merge please. The hope is that with STS we can work around the simultaneous install issue but its not in code yet.

**Review by whitleykeith — APPROVED** [review]
lgtm

**Review by smalleni — APPROVED** [review]

**Comment by smalleni** [comment]
> @smalleni Mind giving this a quick review/merge please. The hope is that with STS we can work around the simultaneous install issue but its not in code yet.

I can merge if I'm given those permissions :)

**Pull request merged**
