### PR TITLE
Rosa ovn

### PR DESCRIPTION
**Pull request by smalleni**
### Description
Enables consumption of the --network-type flag on the CI for deploying OVN clusters in ROSA>

### CODE REVIEW

**Comment by smalleni** [comment]
Need ROSA latest version to be 1.1.8

**Comment by smalleni** [comment]
@dry923 @mukrishn @mohit-sheth @whitleykeith PTAL

Also @whitleykeith / @dry923 can you grant me permissions to request reviews etc on this repo. Thanks

**Comment by morenod** [comment]
Change https://github.com/cloud-bulldozer/airflow-kubernetes/blob/master/dags/openshift_nightlies/config/install/rosa/ovn.json#L6 from "osde2e" to "rosa" so the dags for OVN will use it

**Comment by smalleni** [comment]
> Change https://github.com/cloud-bulldozer/airflow-kubernetes/blob/master/dags/openshift_nightlies/config/install/rosa/ovn.json#L6 from "osde2e" to "rosa" so the dags for OVN will use it

Ah, thanks!

**Comment by jtaleric** [comment]
> @dry923 @mukrishn @mohit-sheth @whitleykeith PTAL
> 
> Also @whitleykeith / @dry923 can you grant me permissions to request reviews etc on this repo. Thanks

Should be fixed

**Comment by smalleni** [comment]
> > @dry923 @mukrishn @mohit-sheth @whitleykeith PTAL
> > Also @whitleykeith / @dry923 can you grant me permissions to request reviews etc on this repo. Thanks
> 
> Should be fixed

Thanks Joe!

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
