### PR TITLE
Dropping SDN, adding 4.13

### PR DESCRIPTION
**Pull request by jtaleric**
Trying to cleanup some of the dags, since the defaults SDN is now OVNK, no need to carry SDN going forward. If we need to spot check, someone can create a branch and run.

Need to confirm with the Managed Services team this is cool to do for ROSA and others.

Signed-off-by: Joe Talerico <jtaleric@redhat.com>

### CODE REVIEW

**Comment by morenod** [comment]
OVN is also default on ROSA

**Review by morenod — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
> OVN is also default on ROSA

let me push a patch to remove sdn then for ROSA...

**Review by rsevilla87 — APPROVED** [review]
Number of hits in tests needs to be updated

```
 >       assert hits == 11
E       assert 6 == 11
```

**Review by afcollins — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
