### PR TITLE
baremetal benchmark script

### PR DESCRIPTION
**Pull request by mukrishn**

### CODE REVIEW

**Comment by mukrishn** [comment]
@whitleykeith PTAL

**Review by whitleykeith — APPROVED** [review]
lgtm

**Comment by mukrishn** [comment]
@mohit-sheth PTAL and merge.

**Review by mohit-sheth — APPROVED** [review]

**Comment by smalleni** [comment]
@mohit-sheth @whitleykeith Can one you nerge these changes for @mukrishn. Thanks!

**Pull request merged**
