### PR TITLE
Adding data-plane-v2

### PR DESCRIPTION
**Pull request by jtaleric**
Add k8s-netperf to our automation.

TODO : Add ROSA, OSD and Baremetal

### CODE REVIEW

**Comment by vishnuchalla** [comment]
Looks like some of the unit test assertions are failing!

**Comment by jtaleric** [comment]
```>       assert hits == 5
52
E       assert 6 == 5```

**Comment by jtaleric** [comment]
> Looks like some of the unit test assertions are failing!

outside of the math problem :)

**Review by rsevilla87 — APPROVED** [review]
lgtm!

**Pull request merged**
