### PR TITLE
ACS: add to production runs

### PR DESCRIPTION
**Pull request by gavin-stackrox**
### Description

This change adds an ACS enabled run. There are also two required secrets that I will communicate separately.

/cc @jtaleric

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I've also created a copy of the benchmarks to override the default for this DAG. In order to use ACS specific metrics.

**Comment by Harshith-umesh** [comment]
@gavin-stackrox you've mentioned about 2 secrets, are they meant to be stored on our vault? https://github.com/cloud-bulldozer/airflow-kubernetes/blob/master/dags/openshift_nightlies/docs/secrets.md and where are they going to be used? during the install or during workload execution?

**Comment by Harshith-umesh** [comment]
ack, so then those vars have to be loaded, for airflow to make use of them. similar to this: https://github.com/cloud-bulldozer/airflow-kubernetes/blob/63adab79206cc5a10295983bbb3d08edfc087968/dags/openshift_nightlies/tasks/install/openshift.py#L37

**Comment by gavin-stackrox** [comment]
FYI I am debugging this change in my airflow playground against the latest e2e-benchmarking (now that https://github.com/cloud-bulldozer/e2e-benchmarking/pull/275 has merged). 

Next steps:

- [ ] get that to a point where it runs
- [ ] can pull metrics after the fact

**Review by whitleykeith — APPROVED** [review]
lgtm

**Comment by whitleykeith** [comment]
> FYI I am debugging this change in my airflow playground against the latest e2e-benchmarking (now that [cloud-bulldozer/e2e-benchmarking#275](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/275) has merged).
> 
> Next steps:
> 
> * [ ]  get that to a point where it runs
> * [ ]  can pull metrics after the fact

for metrics it should just be a matter of enabling thanos in the install json. That would also allow us to generate reports off of those metrics

**Comment by jtaleric** [comment]
> > FYI I am debugging this change in my airflow playground against the latest e2e-benchmarking (now that [cloud-bulldozer/e2e-benchmarking#275](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/275) has merged).
> > Next steps:
> > 
> > * [ ]   get that to a point where it runs
> > * [ ]   can pull metrics after the fact
> 
> for metrics it should just be a matter of enabling thanos in the install json. That would also allow us to generate reports off of those metrics

I think this is more about capturing via kube-burner vs thanos.

**Comment by gavin-stackrox** [comment]
> > > FYI I am debugging this change in my airflow playground against the latest e2e-benchmarking (now that [cloud-bulldozer/e2e-benchmarking#275](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/275) has merged).
> > > Next steps:
> > > 
> > > * [ ]    get that to a point where it runs
> > > * [ ]    can pull metrics after the fact
> > 
> > 
> > for metrics it should just be a matter of enabling thanos in the install json. That would also allow us to generate reports off of those metrics
> 
> I think this is more about capturing via kube-burner vs thanos.

Yes. I think at this point I want to pull metrics (that I've added in e2-benchmarking) after kube-burner workload runs and compare to other runs. I now have two runs that ran to completion to use. I'll reach out on slack if I need help :)

**Comment by gavin-stackrox** [comment]
`touchstone_compare -url ... -u 9a267887-8fc0-4df3-ae78-3fd7da9dd50b 360db898-d602-476e-a4fb-4391a172c303 --config config/kubeburner.json` gives a useful starting point.

Can this PR get merged and an ACS run added to: http://airflow.apps.sailplane.perf.lab.eng.rdu2.redhat.com/home?

**Pull request merged**
